stages:
  - test
  - build
  - deploy

# .unit_test:
#   stage: test
#   image: node
#   script:
# 		- ...

build_docker:
  stage: build
  only:
    - production
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest --build-arg scientia_gid=$SCIENTIA_GID .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy prod:
  stage: deploy
  only:
    - production
  when: manual
  script:
    - docker system prune --all --force
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker stop scientia || true
    - >
        docker run
        --name scientia
        --rm -d
        -p 3000:3000
        -v /yarn:/yarn
        $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  tags:
    - deploy_prod
  environment:
    name: production
    url: https://scientia.doc.ic.ac.uk



