version: "3.9"

services:
  gateway:
    image: gitlab.doc.ic.ac.uk:4567/edtech/scientia-api:master
    environment:
      - ENVIRONMENT=production
      - MATERIALS_ENTRYPOINT=http://materials:5001
      - ABC_ENTRYPOINT=https://abc-api.doc.ic.ac.uk
      - AUTH_JWT_SECRET_KEY
      - API_ROLE_USERNAME
      - API_ROLE_PASSWORD
    deploy:
      mode: replicated
      replicas: 1
  materials:
    image: gitlab.doc.ic.ac.uk:4567/edtech/materials:basic-auth
    environment:
      - ENV=production
      - SECRET_KEY
      - API_ROLE_USERNAME
      - API_ROLE_PASSWORD
      - DB_CONN_STR
      - DB_EDTECH_CONNECTION_STRING
      - STORAGE_ROOT
    volumes:
      - /vol/materials:/vol/materials
    deploy:
      mode: replicated
      replicas: 1
  frontend:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    environment:
      - REACT_APP_API_ENTRYPOINT=https://nova-scientia.doc.ic.ac.uk/api
    deploy:
      mode: replicated
      replicas: 1
  reverse_proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prod-reverse-proxy.conf:/etc/nginx/conf.d/scientia.doc.ic.ac.uk.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - gateway
      - materials
      - frontend
